version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing Node...
      - curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
      - apt install -y nodejs
  build:
    commands:
      - echo Installing dependencies...
      - npm install
  install:
    commands:
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist